---
# Remove packages
- name: Remove packages on Debian/Ubuntu (apt)
  vars:
    pkg_removals: "{{ ubuntu_pkg_removals | select | list }}"
  apt:
    name: "{{ pkg_removals }}"
    state: absent
    update_cache: false
    cache_valid_time: "{{ apt_cache_valid_time }}"
  when: 
    - ansible_facts.os_family == 'Debian'
    - not (offline_mode | default(false))
  become: true

# Install packages
- name: Install packages on Debian/Ubuntu (apt)
  vars:
    pkg_installs: "{{ ubuntu_pkg_install | select | list }}"
  apt:
    name: "{{ pkg_installs }}"
    state: present
    update_cache: "{{ (not offline_mode | default(false)) | bool }}"
    cache_valid_time: "{{ apt_cache_valid_time }}"
  when: 
    - ansible_facts.os_family == 'Debian'
    - not (offline_mode | default(false))
  become: true
